apiVersion: apps/v1
kind: Deployment
metadata:
  name: earztbrief
  labels:
    app: earztbrief
spec:
  replicas: 3
  selector:
    matchLabels:
      app: earztbrief
  template:
    metadata:
      labels:
        app: earztbrief
    spec:
      containers:
      - name: earztbrief
        image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/registry:earztbrief
        ports:
        - containerPort: 80