apiVersion: apps/v1
kind: Deployment
metadata:
  name: earztbrief
  labels:
    app: earztbrief
spec:
  replicas: 3
  selector:
    matchLabels:
      app: earztbrief
  template:
    metadata:
      labels:
        app: earztbrief
    spec:
      containers:
      - name: earztbrief
        image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/earztbrief
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: earztbrief
spec:
  selector:
    app: earztbrief
  ports:
    - port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - earztbrief.med-united.health
    secretName: earztbrief-tls
  rules:
  - host: earztbrief.med-united.health
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: earztbrief
              port:
                number: 80
        - path: /sendEmail
          pathType: Prefix
          backend:
            service:
              name: earztbrief-sender
              port:
                number: 8080
  
